apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsbone-app
  namespace: default
  labels:
    app: fsbone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fsbone-app
  template:
    metadata:
      labels:
        app: fsbone-app
    spec:
      initContainers:
      - name: env-checker
        image: busybox
        command: ['sh', '-c', 'echo "=== Environment Variables ==="; env | sort']
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: NEXTAUTH_URL
          value: "https://www.fsbone.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: fsbone-secrets
              key: NEXTAUTH_SECRET
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_BUCKET_NAME
          value: "fsbone-bucket"
        - name: NEXT_PUBLIC_AWS_REGION
          value: "ap-northeast-2"
        - name: NEXT_PUBLIC_AWS_BUCKET_NAME
          value: "fsbone-bucket"
      containers:
      - name: fsbone-app
        image: 864981727549.dkr.ecr.ap-northeast-2.amazonaws.com/fsbone-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: NEXTAUTH_URL
          value: "https://www.fsbone.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: fsbone-secrets
              key: NEXTAUTH_SECRET
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_BUCKET_NAME
          value: "fsbone-bucket"
        - name: NEXT_PUBLIC_AWS_REGION
          value: "ap-northeast-2"
        - name: NEXT_PUBLIC_AWS_BUCKET_NAME
          value: "fsbone-bucket"
