apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fsbone-cluster
  region: ap-northeast-2  # 서울 리전
  version: "1.27"        # 쿠버네티스 버전

# VPC 설정
vpc:
  cidr: "192.168.0.0/16"  # VPC CIDR 범위
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  nat:
    gateway: Single     # NAT 게이트웨이 설정

# 노드 그룹 설정
managedNodeGroups:
  - name: fsbone-nodes
    instanceType: t3.medium  # 인스턴스 타입
    minSize: 2              # 최소 노드 수
    maxSize: 4              # 최대 노드 수
    desiredCapacity: 2      # 희망 노드 수
    volumeSize: 20          # EBS 볼륨 크기(GB)
    privateNetworking: true
    labels: 
      role: worker
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true  # ECR 접근 권한
        autoScaler: true    # 오토스케일링 권한
        albIngress: true    # ALB 인그레스 권한
        cloudWatch: true    # CloudWatch 권한

# 애드온 설정
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

# CloudWatch 로깅 설정
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]    # 모든 로그 타입 활성화