apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fsbone-cluster
  region: ap-northeast-2  # 서울 리전
  version: "1.27"        # 쿠버네티스 버전

# VPC 설정
vpc:
  cidr: "192.168.0.0/16"  # VPC CIDR 범위
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  nat:
    gateway: Single     # NAT 게이트웨이 설정

# 노드 그룹 설정
managedNodeGroups:
  - name: fsbone-nodes-small
    instanceType: t3.small
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    labels: 
      role: worker
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albIngress: true
        cloudWatch: true

# 애드온 설정
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

# CloudWatch 로깅 설정
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]