name: Deploy to EKS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Debug environment variables
      env:
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        AUTH_URL: ${{ secrets.AUTH_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      run: |
        echo "Checking environment variables..."
        echo "AUTH_SECRET exists: ${{ secrets.AUTH_SECRET != '' }}"
        echo "AUTH_URL exists: ${{ secrets.AUTH_URL != '' }}"
        echo "DATABASE_URL exists: ${{ secrets.DATABASE_URL != '' }}"
        echo "DATABASE_HOST exists: ${{ secrets.DATABASE_HOST != '' }}"
        echo "DATABASE_USER exists: ${{ secrets.DATABASE_USER != '' }}"
        echo "DATABASE_PASSWORD exists: ${{ secrets.DATABASE_PASSWORD != '' }}"
        echo "DATABASE_NAME exists: ${{ secrets.DATABASE_NAME != '' }}"
        echo "DATABASE_PORT exists: ${{ secrets.DATABASE_PORT != '' }}"

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: 864981727549.dkr.ecr.ap-northeast-2.amazonaws.com
        ECR_REPOSITORY: fsbone-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building Docker image..."
        docker build \
          --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
          --build-arg AUTH_URL=${{ secrets.AUTH_URL }} \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --build-arg DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
          --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
          --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          --build-arg DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
          -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}